# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epic', '0001_initial'),
        ('namespace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_no', models.IntegerField(blank=True, null=True)),
                ('initial_point_size', models.IntegerField(default=0)),
                ('progress_point_size', models.IntegerField(default=0)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namespace.NameSpace')),
            ],
        ),
        migrations.CreateModel(
            name='SprintSlotEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_point', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('point_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sprint_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.SprintSlot')),
            ],
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.SprintSlot')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Task')),
            ],
        ),
    ]
