# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0010_auto_20170313_1100'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintslot',
            name='data',
            field=models.TextField(default=b'null'),
        ),
        migrations.AlterUniqueTogether(
            name='sprinttask',
            unique_together=set([('sprint_slot', 'task')]),
        ),
    ]
