# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_auto_20170228_0546'),
        ('testsuite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectreport',
            old_name='relate_defect_tasks',
            new_name='relate_tasks',
        ),
        migrations.RenameField(
            model_name='testrecord',
            old_name='test_case',
            new_name='testcase',
        ),
        migrations.AddField(
            model_name='defectreport',
            name='relate_stories',
            field=models.ManyToManyField(to='epic.Story'),
        ),
        migrations.RemoveField(
            model_name='epictestcase',
            name='testsuite',
        ),
        migrations.AddField(
            model_name='epictestcase',
            name='testsuite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testsuite.EpicTestSuite'),
            preserve_default=False,
        ),
    ]
