# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0002_auto_20170314_0523'),
        ('testsuite', '0004_auto_20170424_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='key',
        ),
        migrations.RemoveField(
            model_name='testround',
            name='tester',
        ),
        migrations.AddField(
            model_name='epictestcase',
            name='state',
            field=models.CharField(choices=[('PP', 'Prepare'), ('DONE', 'Done')], default='PP', max_length=20),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_testrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='developer_question_or_remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='developer_state',
            field=models.CharField(choices=[('W8_TEST', 'Waiting test'), ('PASS', 'Test pass'), ('FAIL', 'Test fail'), ('SKIP', 'Skip test'), ('RECONS', 'Re consider')], default='W8_TEST', max_length=20),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='expected_results',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_results',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_steps',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='testround',
            name='sprintslot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sprintslot_testround', to='sprint.SprintSlot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='state',
            field=models.CharField(choices=[('W8_TEST', 'Waiting test'), ('PASS', 'Test pass'), ('FAIL', 'Test fail'), ('SKIP', 'Skip test'), ('RECONS', 'Re consider')], default='W8_TEST', max_length=20),
        ),
        migrations.AlterField(
            model_name='testround',
            name='state',
            field=models.CharField(choices=[('PP', 'Prepare'), ('IP', 'In-progress'), ('W8RV', 'Generate Report and waiting review'), ('DONE', 'Done')], default='PP', max_length=20),
        ),
    ]
