# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namespace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_state', models.CharField(choices=[(b'PP', b'PP'), (b'RD-DEV', b'Ready-for-dev'), (b'INP', b'In-progress'), (b'DN', b'Done'), (b'CC', b'Cancel')], default=b'PP', max_length=10)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default=b'null')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('icon_url', models.CharField(max_length=256)),
                ('desc', models.TextField(default='null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_epic_creator_related', related_query_name='epic_epics_creator', to=settings.AUTH_USER_MODEL)),
                ('epicmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epic_manager', to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namespace.NameSpace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpicMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default=b'null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_epicmember_creator_related', related_query_name='epic_epicmembers_creator', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Epic')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpicSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('approve_dttm', models.DateTimeField(auto_now_add=True)),
                ('reject_dttm', models.DateTimeField(auto_now_add=True)),
                ('approve_state', models.CharField(choices=[(b'PP', b'Prepare'), (b'RQ_APP', b'Request for approve'), (b'RQ_APP_RJ_ASK', b'Reject ask'), (b'RQ_APP_RJ_AC', b'Reject accepted'), (b'RQ_APP_RJ_NOT-AC', b'Reject not accepted'), (b'APPV', b'Approved'), (b'CHG_PP', b'Change prepare')], default=b'PP', max_length=20)),
                ('data', models.TextField(default=b'null')),
                ('name', models.CharField(max_length=128)),
                ('spec_type', models.CharField(choices=[('UC', 'Usecase'), ('UX_UI', 'UX-UI'), ('SEQD', 'Sequence-diagram'), ('API', 'API-Spec')], default='UC', max_length=10)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epic_epicspec_approver_related', related_query_name='epic_epicspecs_approver', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_epicspec_creator_related', related_query_name='epic_epicspecs_creator', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Epic')),
                ('rejector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epic_epicspec_rejector_related', related_query_name='epic_epicspecs_rejector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'spec_info',
            },
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('ref_event_key', models.CharField(max_length=256)),
                ('ref_item_key', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_messageroom_creator_related', related_query_name='epic_messagerooms_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_state', models.CharField(choices=[(b'PP', b'PP'), (b'RD-DEV', b'Ready-for-dev'), (b'INP', b'In-progress'), (b'DN', b'Done'), (b'CC', b'Cancel')], default=b'PP', max_length=10)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(default='null')),
                ('data', models.TextField(default='null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_story_creator_related', related_query_name='epic_storys_creator', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_story', to='epic.Epic')),
            ],
            options={
                'abstract': False,
                'db_table': 'story_info',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(default='null')),
                ('data', models.TextField(default='null')),
                ('estimate_hr', models.FloatField(default=1.0)),
                ('sprint_no', models.IntegerField(blank=True, null=True)),
                ('actual_hr', models.FloatField(blank=True, null=True)),
                ('task_state', models.CharField(choices=[('PP', 'Draft'), ('TODO', 'To-do'), ('INP', 'In-progress'), ('TV', 'To-verify'), ('TEST-F', 'Test-fail'), ('TEST-P', 'Test-pass'), ('DN', 'Done'), ('CC', 'Cancel')], default='PP', max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_task_creator_related', related_query_name='epic_tasks_creator', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Epic')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responder', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Story')),
            ],
            options={
                'abstract': False,
                'db_table': 'task_info',
            },
        ),
        migrations.AddField(
            model_name='epicspec',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Story'),
        ),
    ]
