# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_remove_epicspec_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicspec',
            name='relate_stories',
            field=models.ManyToManyField(to='epic.Story'),
        ),
        migrations.AddField(
            model_name='epicspec',
            name='relate_tasks',
            field=models.ManyToManyField(to='epic.Task'),
        ),
    ]
