# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0004_remove_epic_epicmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='epic.Epic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.CharField(choices=[('PP', 'Prepare'), ('TODO', 'To-do'), ('INP', 'In-progress'), ('TV', 'To-verify'), ('VING', 'To-verify'), ('TEST-F', 'Test-fail'), ('TEST-P', 'Test-pass'), ('DN', 'Done'), ('PD', 'Pending'), ('CC', 'Cancel')], default='PP', max_length=10),
        ),
    ]
