# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0005_auto_20170313_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Epic'),
        ),
    ]
