# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0006_auto_20170313_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='epic.Epic'),
            preserve_default=False,
        ),
    ]
