# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0007_auto_20170313_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='base_state',
            field=models.CharField(choices=[(b'PP', b'Prepare'), (b'RD-DEV', b'Ready-for-dev'), (b'INP', b'In-progress'), (b'DN', b'Done'), (b'CC', b'Cancel')], default=b'PP', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='base_state',
            field=models.CharField(choices=[(b'PP', b'Prepare'), (b'RD-DEV', b'Ready-for-dev'), (b'INP', b'In-progress'), (b'DN', b'Done'), (b'CC', b'Cancel')], default=b'PP', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Epic'),
        ),
    ]
