# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0008_auto_20170313_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='epic',
        ),
    ]
