# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic', '0009_remove_task_epic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_state', models.CharField(choices=[(b'PP', b'Prepare'), (b'RD-DEV', b'Ready-for-dev'), (b'INP', b'In-progress'), (b'DN', b'Done'), (b'CC', b'Cancel')], default=b'PP', max_length=10)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(default='null')),
                ('data', models.TextField(default='null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_issue_creator_related', related_query_name='epic_issues_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Issue'),
        ),
    ]
