# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=8, unique=True)),
                ('desc', models.TextField(default='null')),
                ('data', models.TextField(default='null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_namespace_creator_related', related_query_name='namespace_namespaces_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NameSpaceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default=b'null')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_namespacemember_creator_related', related_query_name='namespace_namespacemembers_creator', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namespace.NameSpace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
